[theme]
primaryColor="#726afe"
backgroundColor="#c7c3fe"
secondaryBackgroundColor="#cfcff9"
textColor="#665dff"

[client]































































































showSidebarNavigation = false
